<?php

namespace AudreyCuisineBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Retourne les X derniers articles postés
     * @param  integer $nb [Nombre d'articles à retourner]
     * @return Category[]       [Tableau d'entité Category]
     */
    public function getLastPosts(int $nb = 4): array {
        $posts = $this->findBy(
            ['isVisible' => 1],
            ['updated' => 'DESC'],
            $nb
        );
        return $this->toArray($posts);
    }

    /**
     * Formate un tableau d'entité en tableau prêt à être affiché
     * @param  Post[] $posts [description]
     * @return array        [description]
     */
    private function toArray(array $posts): array {
        $result = [];
        foreach ($posts as $keyPost => $Post) {
            // Récupération des catégoriees de l'article
            $categories = [];
            foreach ($Post->getCategory() as $keyCat => $Category) {
                $categories[$keyCat] = array(
                    'name' => $Category->getName()
                );
            }

            $result[$keyPost] = array(
                'title' => $Post->getTitle(),
                'content' => $Post->getContent(),
                'updated' => $Post->getUpdated()->format(\Datetime::ISO8601), // Date au format ISO
                'category' => $categories
            );
        }
        return $result;
    }
}
