<?php

namespace AudreyCuisineBundle\Repository;

use AudreyCuisineBundle\Entity\Post;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Recherche d'articles à partir des termes
     * @param  string $terms [Termes à rechercher]
     * @return array         [Résultat de la requête]
     */
    public function searchPostsByTerms(string $terms): array {
        $qb = $this->createQueryBuilder('p')
            ->where("p.title LIKE :terms")
            ->orderBy('p.updated', 'DESC')
            ->setParameter('terms', '%'.$terms.'%')
            ->getQuery();
        return $qb->getResult();
    }

    /**
     * Retourne les entités Post appartenant à une catégorie à partir de son slug
     * @param  string $slug [Slug de la catégorie]
     * @return Post[]        [Liste des articles]
     */
    public function getPostsInCategory(string $slug) {
        $qb = $this->createQueryBuilder('p');
        $query = $qb->select('p as post, c.name as category')
            ->join('p.category', 'c')
            ->where('c.slug = :categorySlug')
            ->orderBy('p.updated', 'DESC')
            ->setParameter('categorySlug', $slug)
            ->getQuery();
        return $query->getResult();
    }

}
