<?php

namespace AudreyCuisineBundle\Repository;

/**
 * SelectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SelectionRepository extends \Doctrine\ORM\EntityRepository
{

    //

}
