<?php

namespace AudreyCuisineBundle\Repository;

/**
 * TopMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
