services:
#    audrey_cuisine.example:
#        class: AudreyCuisineBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    audrey_cuisine.entity_manager:
        class: AudreyCuisineBundle\Manager\EntityManager
        arguments: ["@doctrine.orm.entity_manager"]
