version: '2'
services:
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        volumes_from:
            - app
        depends_on:
            - php
        links:
            - php
        container_name: "conteneur_nginx"
    php:
        build: ./php
        volumes_from:
            - app
        expose:
            - "9000"
        links:
            - mariadb
        container_name: "conteneur_php"
    mariadb:
        image: mariadb
        volumes:
            - data
        container_name: "conteneur_mariadb"
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "audreycuisine.fr"
            MYSQL_USER: "audrey"
            MYSQL_PASSWORD: "audrey"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mariadb
        depends_on:
            - mariadb
        environment:
            PMA_HOST: mariadb
            PMA_PORT: 3306
        ports:
            - "8080:80"
        container_name: "conteneur_phpmyadmin"
    app:
        image: "php:7.1-fpm"
        volumes:
            - /home/docker/app:/var/www/html
    data:
        image: "php:7.1-fpm"
        volumes:
            - /home/docker/db:/var/lib/mysql
